import { TEAM_STATUSES, TeamStatus } from "../../../lib/constants/statuses";
import { TeamMember } from "./types";

export const mockTeam: TeamMember[] = [
  {
    id: "u-1",
    name: "Admin User",
    initials: "AD",
    role: "Office Admin",
    status: TEAM_STATUSES.ACTIVE as TeamStatus,
    pin: "4821",
    email: "admin@realstone.com",
    phone: "404-555-0199",
    isInstaller: false,
  },
  {
    id: "u-2",
    name: "Juan Perez",
    initials: "JP",
    role: "Lead Installer",
    status: TEAM_STATUSES.ON_SITE as TeamStatus,
    pin: "8823",
    email: "jperez@realstone.com",
    phone: "404-555-0122",
    job_id: "WO-8402",
    isInstaller: true,
  },
  {
    id: "u-3",
    name: "Carlos Ruiz",
    initials: "CR",
    role: "Installer",
    status: TEAM_STATUSES.ON_SITE as TeamStatus,
    pin: "1102",
    email: "cruiz@realstone.com",
    phone: "404-555-0133",
    job_id: "WO-8418",
    isInstaller: true,
  },
  {
    id: "u-4",
    name: "Michael Scott",
    initials: "MS",
    role: "Operations Manager",
    status: TEAM_STATUSES.ACTIVE as TeamStatus,
    pin: "9982",
    email: "mscott@realstone.com",
    phone: "404-555-0144",
    isInstaller: false,
  },
  {
    id: "u-5",
    name: "David Silva",
    initials: "DS",
    role: "Installer",
    status: TEAM_STATUSES.OFFLINE as TeamStatus,
    pin: "5541",
    email: "dsilva@realstone.com",
    phone: "404-555-0155",
    isInstaller: true,
  },
];
